---
abstract: 'Get useful data from e-mail addresses'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Finger
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.00
  DateTime: 0
  Digest::MD5: 2.00
  Digest::SHA1: 2.00
  Getopt::Long: 0
  HTTP::Link::Parser: 0.03
  LWP::Simple: 5.00
  LWP::UserAgent: 5.00
  Pod::Usage: 0
  RDF::Query: 2.200
  RDF::Query::Client: 0.02
  RDF::Trine: 0.112
  URI: 1.30
  XML::LibXML: 1.60
  XRD::Parser: 0.04
  perl: 5.8.1
resources:
  bugtracker: http://search.cpan.org/dist/WWW-Finger/
  homepage: http://search.cpan.org/dist/WWW-Finger/
  license: http://dev.perl.org/licenses/
version: 0.05
